INSERT INTO agent_metadata (
    id, icon, name, name_i18n, description, description_i18n,
    backend, agent_type, agent_source, agent_source_info,
    enabled, command, args, env, native_skills_dirs,
    behavior_policy, yolo_id, agent_capabilities, auth_methods,
    config_options, available_modes, available_models, available_commands,
    sort_order, created_at, updated_at
)
VALUES (
    'codex-app-server-experimental',
    '/api/assets/logos/tools/coding/codex.svg',
    'Codex App Server Experimental',
    NULL,
    'Experimental native Codex app-server lane detected from the Codex CLI installation.',
    NULL,
    'codex-app-server',
    'codex-app-server',
    'builtin',
    '{"binary_name":"codex","detected_from":"codex"}',
    1,
    'codex',
    '["app-server","--listen","stdio://"]',
    '[]',
    '[".codex/skills"]',
    '{"supports_side_question":false,"supports_team":false}',
    'full-access',
    '{"load_session":false,"mcp_capabilities":{"stdio":false,"http":false,"sse":false},"prompt_capabilities":{"audio":false,"embedded_context":false,"image":false},"session_capabilities":{}}',
    NULL,
    NULL,
    '{"current_mode_id":"full-access","available_modes":[{"id":"full-access","name":"Full Access","description":"Codex can edit files and run commands without approval."}]}',
    NULL,
    NULL,
    1460,
    strftime('%s','now') * 1000,
    strftime('%s','now') * 1000
)
ON CONFLICT(id) DO UPDATE SET
    icon = excluded.icon,
    name = excluded.name,
    description = excluded.description,
    backend = excluded.backend,
    agent_type = excluded.agent_type,
    agent_source = excluded.agent_source,
    agent_source_info = excluded.agent_source_info,
    command = excluded.command,
    args = excluded.args,
    env = excluded.env,
    native_skills_dirs = excluded.native_skills_dirs,
    behavior_policy = excluded.behavior_policy,
    yolo_id = excluded.yolo_id,
    agent_capabilities = excluded.agent_capabilities,
    available_modes = excluded.available_modes,
    sort_order = excluded.sort_order,
    updated_at = excluded.updated_at;
